//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_baseline : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean xbrotate
        {
            get
            {
                return SteamVR_Actions.baseline_xbrotate;
            }
        }
        
        public virtual SteamVR_Action_Boolean yarotate
        {
            get
            {
                return SteamVR_Actions.baseline_yarotate;
            }
        }
        
        public virtual SteamVR_Action_Vector2 rightRocker
        {
            get
            {
                return SteamVR_Actions.baseline_rightRocker;
            }
        }
        
        public virtual SteamVR_Action_Vector2 leftRocker
        {
            get
            {
                return SteamVR_Actions.baseline_leftRocker;
            }
        }
        
        public virtual SteamVR_Action_Boolean select
        {
            get
            {
                return SteamVR_Actions.baseline_select;
            }
        }
    }
}
